### ISSUE TITLE
Information is missing in the readme file 

### ISSUE THREAD

**Issue by nkcool5** [SubhasisMukh/virustotal-vt3#1]
### Readme file needs to be updated 

This is just a suggestion, please provide sufficient information about the codes and files like -- how to use them.
This will help the community to use your codes.

Thanks

**Comment by SubhasisMukh** [comment]
Thanks for creating the issue. Will do it as soon as possible.

**Comment by SubhasisMukh** [comment]
README has been updated. Closing the issue.
